language: generic
sudo: required

# tell Travis we need a copy of docker running
services:
  - docker

# tell Travis to build our image using Dockerfile.dev
before_install:
  - docker build -t scottstark/docker-react -f Dockerfile.dev .

# tell Travis to run our test suite in CI-mode
# tests will run only once instead of launching the watcher.
# any return code other than 0 Travis will assume as failure
script:
  - docker run -e CI=true scottstark/docker-react npm run test

# tell Travis how to deploy our application to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-950044734043"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
